controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
apiLogin:
    path: /api/login
    controller: App\Controller\Api\SecurityApiController::login
    methods: POST
